<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Management Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            line-height: 1.6;
        }

        header {
            text-align: center;
            margin-bottom: 20px;
        }

        h1 {
            color: #333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .report-summary {
            margin-bottom: 20px;
        }

        .report-details {
            margin-bottom: 30px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            color: #888;
        }
    </style>
</head>
<body>

    <header>
        <h1>Rapport :</h1>
        <p>Date: {{$dateRapport}}</p>
    </header>

    <div class="report-summary">
        <h2>Summary:</h2>
        <p>Total Orders Received: <strong>{{$commandesValiderNumber}}</strong></p>
        <p>Total Orders Processed: <strong>{{$commandesCreateNumber}}</strong></p>
        <p>Total Orders Pending: <strong>{{$commandesNonValiderNumber}}</strong></p>
    </div>

    <div class="report-details">
        <h2>Details:</h2>
        <p>As of {{$dateRapport}}, the total number of orders processed is {{$commandesCreateNumber}}.</p>
        <p>Breakdown of processed orders:</p>
        <ul>
            <li>{{$commandesCreateNumber}} orders successfully processed.</li>
            <li>{{$commandesNonValiderNumber}} orders pending completion.</li>
        </ul>
    </div>

    <div class="footer">
        <p>Generated by Your Stock Management App</p>
    </div>

</body>
</html>
